### ISSUE TITLE
Add option to hide nginx server version

### ISSUE THREAD

**Issue by sebthom** [alekseydemidov/pla-ssp#3]
Please either:
1. simply specify `server_tokens off` by default in /etc/nginx/conf.d/ssp-nginx.conf and /etc/nginx/conf.d/pla-nginx.conf , or
1. add an environment variable so that the server_tokens can be enabled/disabled

I think just doing option 1. would sensible.

**Comment by alekseydemidov** [comment]
Hi Sebastian, thank you for your attention.
Sorry for delay, this option added as an environment variable NGINX_SERVER_VERSION
https://github.com/alekseydemidov/pla-ssp/commit/37c1f83b123181859c743e642f21dbb8fd19951b

**Comment by sebthom** [comment]
Thanks!!
